# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upD3gkadJcxT-5srygTXeqgLhMU2u-KV
"""

# ============================================================
# Qwen2.5-VL BASE MODEL LogProb TTA SUBMISSION ONLY
# FULL COLAB CODE - FIXED TOKENIZERS VERSION
#
# - Adapter 없음
# - 제출용 고정: test 전체 inference 후 submission 저장
# - Drive는 /content/gdrive_real 에 강제 마운트
# - qwen_vl_utils 사용 안 함
# - torchvision 사용 안 함
# - bitsandbytes 사용 안 함
# - torch 재설치 안 함
# - transformers==4.51.3 에 맞춰 tokenizers==0.21.4 고정
# ============================================================

# ============================================================
# 0. SAFE PACKAGE FIX
# ============================================================

import sys
import subprocess

# torchvision은 지금 qwen_vl_utils를 안 쓰므로 필요 없습니다.
# 예전 꼬인 torchvision이 AutoProcessor import를 터뜨렸기 때문에 제거합니다.
subprocess.call([sys.executable, "-m", "pip", "uninstall", "-y", "torchvision"])

# 핵심: transformers 4.51.3은 tokenizers>=0.21,<0.22 필요
# tokenizers 0.22.x가 깔리면 import에서 바로 터짐
subprocess.check_call([
    sys.executable, "-m", "pip", "install", "-q", "--no-cache-dir", "--upgrade",
    "transformers==4.51.3",
    "tokenizers==0.21.4",
    "accelerate==1.8.1",
    "pillow==10.4.0",
    "safetensors==0.5.3",
    "huggingface-hub==0.30.2",
    "pandas",
    "tqdm",
])

print("Package fix finished.")
print("IMPORTANT: if import still fails, run this cell once more, then continue.")

# ============================================================
# 1. IMPORTS
# ============================================================

import os
import re
import itertools
import shutil
from pathlib import Path
from collections import defaultdict

import torch
import torch.nn.functional as F
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

import transformers
import tokenizers

print("transformers:", transformers.__version__)
print("tokenizers:", tokenizers.__version__)
assert transformers.__version__ == "4.51.3"
assert tokenizers.__version__.startswith("0.21."), tokenizers.__version__

from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("cuda version:", torch.version.cuda)

# ============================================================
# 2. FORCE REAL DRIVE MOUNT
# ============================================================

from google.colab import drive

MOUNT_POINT = Path("/content/gdrive_real")

if (MOUNT_POINT / "MyDrive").exists():
    print("Drive already mounted at:", MOUNT_POINT)
else:
    if MOUNT_POINT.exists():
        shutil.rmtree(MOUNT_POINT, ignore_errors=True)

    MOUNT_POINT.mkdir(parents=True, exist_ok=True)
    drive.mount(str(MOUNT_POINT), force_remount=True)

MYDRIVE = MOUNT_POINT / "MyDrive"
assert MYDRIVE.exists(), f"MyDrive not found: {MYDRIVE}"

print("MYDRIVE:", MYDRIVE)
print("Top-level MyDrive items:")
for p in list(MYDRIVE.iterdir())[:80]:
    print(" -", p)

# ============================================================
# 3. FIXED PATHS: SUBMISSION ONLY
# ============================================================

DATA_DIR = MYDRIVE / "보보" / "snuaichallenge" / "snuaichallenge_data-2"
OUTPUT_DIR = MYDRIVE / "보보" / "snu_ai_challenge_qwen25vl_base_none_submission"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BASE_MODEL_NAME = "Qwen/Qwen2.5-VL-3B-Instruct"

TRAIN_CSV = DATA_DIR / "train.csv"
TEST_CSV = DATA_DIR / "test.csv"
SAMPLE_CSV = DATA_DIR / "sample_submission.csv"
TRAIN_IMG_DIR = DATA_DIR / "train"
TEST_IMG_DIR = DATA_DIR / "test"

print("\n=== PATH CHECK ===")
print("DATA_DIR:", DATA_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

for name, path in [
    ("train.csv", TRAIN_CSV),
    ("test.csv", TEST_CSV),
    ("sample_submission.csv", SAMPLE_CSV),
    ("train folder", TRAIN_IMG_DIR),
    ("test folder", TEST_IMG_DIR),
]:
    print(f"{name}: {path.exists()} | {path}")

assert TRAIN_CSV.exists(), f"Missing train.csv: {TRAIN_CSV}"
assert TEST_CSV.exists(), f"Missing test.csv: {TEST_CSV}"
assert SAMPLE_CSV.exists(), f"Missing sample_submission.csv: {SAMPLE_CSV}"
assert TRAIN_IMG_DIR.exists(), f"Missing train folder: {TRAIN_IMG_DIR}"
assert TEST_IMG_DIR.exists(), f"Missing test folder: {TEST_IMG_DIR}"

# ============================================================
# 4. LOAD DATA
# ============================================================

test_df = pd.read_csv(TEST_CSV, dtype={"Id": str})
sample_df = pd.read_csv(SAMPLE_CSV, dtype={"Id": str})

print("\n=== DATA ===")
print("test:", test_df.shape)
print("sample:", sample_df.shape)
print(test_df.head())

assert "Id" in test_df.columns
assert "Sentence" in test_df.columns
for i in range(1, 5):
    assert f"Input_{i}" in test_df.columns, f"Missing column Input_{i}"

assert list(sample_df.columns) == ["Id", "Answer"], sample_df.columns
assert len(test_df) == len(sample_df), (len(test_df), len(sample_df))

# ============================================================
# 5. ORDER UTILS
# ============================================================

PERMS = list(itertools.permutations([1, 2, 3, 4]))

def parse_answer(x):
    vals = list(map(int, re.findall(r"\d+", str(x))))
    if len(vals) != 4 or sorted(vals) != [1, 2, 3, 4]:
        raise ValueError(f"Invalid answer: {x}")
    return vals

def order_to_rank(order):
    """
    chronological order of original Input indices -> competition Answer format.
    Example:
        order [4,1,3,2] -> rank [2,4,3,1]
    """
    order = list(map(int, order))
    rank = [None] * 4
    for temporal_pos, input_idx in enumerate(order, start=1):
        rank[input_idx - 1] = temporal_pos
    return rank

def answer_to_str(vals):
    return "[" + ", ".join(map(str, map(int, vals))) + "]"

def is_perm(vals):
    vals = list(map(int, vals))
    return len(vals) == 4 and sorted(vals) == [1, 2, 3, 4]

assert order_to_rank([4, 1, 3, 2]) == [2, 4, 3, 1]
print("Order utils OK")

# ============================================================
# 6. IMAGE UTILS
# ============================================================

def image_paths_for_row(row, image_root: Path):
    row_id = str(row["Id"])
    folder = image_root / row_id
    paths = []
    for i in range(1, 5):
        p = folder / str(row[f"Input_{i}"])
        paths.append(p)
    return paths

def load_pil_images(paths):
    images = []
    for p in paths:
        if not p.exists():
            raise FileNotFoundError(f"Image not found: {p}")
        with Image.open(p) as img:
            images.append(img.convert("RGB").copy())
    return images

print("\n=== IMAGE PATH QUICK CHECK ===")
for idx in range(min(3, len(test_df))):
    row = test_df.iloc[idx]
    ps = image_paths_for_row(row, TEST_IMG_DIR)
    print(row["Id"], [p.exists() for p in ps], ps)

# ============================================================
# 7. LOAD BASE QWEN2.5-VL
# ============================================================

torch.backends.cuda.matmul.allow_tf32 = True

if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
    COMPUTE_DTYPE = torch.bfloat16
elif torch.cuda.is_available():
    COMPUTE_DTYPE = torch.float16
else:
    COMPUTE_DTYPE = torch.float32

print("\n=== MODEL LOAD ===")
print("COMPUTE_DTYPE:", COMPUTE_DTYPE)

# 제출용 고정값
MIN_PIXELS = 128 * 28 * 28
MAX_PIXELS = 512 * 28 * 28

print("Loading processor...")
processor = AutoProcessor.from_pretrained(
    BASE_MODEL_NAME,
    trust_remote_code=True,
    min_pixels=MIN_PIXELS,
    max_pixels=MAX_PIXELS,
)

print("Loading base model...")
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    BASE_MODEL_NAME,
    trust_remote_code=True,
    torch_dtype=COMPUTE_DTYPE,
    device_map="auto",
    attn_implementation="eager",
)

model.eval()

try:
    MODEL_DEVICE = next(model.parameters()).device
except StopIteration:
    MODEL_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Model loaded OK")
print("MODEL_DEVICE:", MODEL_DEVICE)
print("hf_device_map:", getattr(model, "hf_device_map", None))

# ============================================================
# 8. PROMPT / TTA
# ============================================================

# 제출용 고정: balanced4
TTA_PERMS = [
    (1, 2, 3, 4),
    (2, 3, 4, 1),
    (3, 4, 1, 2),
    (4, 1, 2, 3),
]

print("\nTTA fixed: balanced4, num_tta =", len(TTA_PERMS))

def build_prompt(sentence):
    return (
        "You are given four shuffled frames from the same video and a sentence describing the event.\n"
        "Infer the chronological order of the frames.\n"
        "Focus on action progress, pose changes, object position changes, contact state, and before/after states.\n"
        "Do not rely on the input order.\n"
        "Output only the chronological order as a Python list of image numbers.\n"
        "Example output: [3, 1, 2, 4]\n\n"
        f"Sentence: {sentence}"
    )

def make_messages(sentence, num_images=4):
    content = []
    for _ in range(num_images):
        content.append({"type": "image"})
    content.append({"type": "text", "text": build_prompt(sentence)})
    return [{"role": "user", "content": content}]

def move_inputs_to_device(inputs, device):
    out = {}
    for k, v in inputs.items():
        if torch.is_tensor(v):
            out[k] = v.to(device)
        else:
            out[k] = v
    return out

# ============================================================
# 9. LOGPROB SCORING WITHOUT qwen_vl_utils / torchvision
# ============================================================

@torch.inference_mode()
def score_one_candidate(sentence, displayed_image_paths, candidate_display_order):
    """
    candidate_display_order:
        displayed image 번호 기준 chronological order.
        예: (2, 4, 1, 3)
    """

    messages = make_messages(sentence, num_images=4)

    prefix_text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    pil_images = load_pil_images(displayed_image_paths)

    prefix_inputs = processor(
        text=[prefix_text],
        images=pil_images,
        videos=None,
        padding=True,
        return_tensors="pt",
    )

    target_text = answer_to_str(candidate_display_order)

    target_ids = processor.tokenizer(
        target_text,
        add_special_tokens=False,
        return_tensors="pt",
    ).input_ids

    input_ids_cpu = torch.cat([prefix_inputs["input_ids"], target_ids], dim=1)
    attention_mask_cpu = torch.cat(
        [
            prefix_inputs["attention_mask"],
            torch.ones_like(target_ids),
        ],
        dim=1,
    )

    labels_cpu = torch.full_like(input_ids_cpu, -100)
    labels_cpu[:, -target_ids.shape[1]:] = target_ids

    model_inputs = dict(prefix_inputs)
    model_inputs["input_ids"] = input_ids_cpu
    model_inputs["attention_mask"] = attention_mask_cpu

    model_inputs = move_inputs_to_device(model_inputs, MODEL_DEVICE)
    labels = labels_cpu.to(MODEL_DEVICE)
    input_ids = input_ids_cpu.to(MODEL_DEVICE)

    outputs = model(**model_inputs)
    logits = outputs.logits

    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = labels[:, 1:].contiguous()
    shift_targets = input_ids[:, 1:].contiguous()

    mask = shift_labels.ne(-100)

    log_probs = F.log_softmax(shift_logits.float(), dim=-1)
    selected = log_probs.gather(-1, shift_targets.unsqueeze(-1)).squeeze(-1)

    token_logprob_sum = selected[mask].sum().item()
    token_count = int(mask.sum().item())
    avg_logprob = token_logprob_sum / max(token_count, 1)

    del outputs, logits, shift_logits, shift_labels, shift_targets, log_probs, selected
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return avg_logprob

def predict_row(row, image_root: Path):
    sentence = str(row["Sentence"])
    original_paths = image_paths_for_row(row, image_root)

    agg_scores = defaultdict(list)

    for input_perm in TTA_PERMS:
        # input_perm: displayed position -> original input index
        displayed_paths = [original_paths[i - 1] for i in input_perm]

        for cand_display_order in PERMS:
            # candidate displayed-label order -> original Input-index order
            cand_original_order = tuple(input_perm[pos - 1] for pos in cand_display_order)

            score = score_one_candidate(
                sentence=sentence,
                displayed_image_paths=displayed_paths,
                candidate_display_order=cand_display_order,
            )

            agg_scores[cand_original_order].append(score)

    mean_scores = {
        order: float(sum(scores) / len(scores))
        for order, scores in agg_scores.items()
    }

    best_order = max(mean_scores.items(), key=lambda x: x[1])[0]
    best_order = list(best_order)
    best_rank = order_to_rank(best_order)

    top5 = sorted(mean_scores.items(), key=lambda x: x[1], reverse=True)[:5]
    return best_order, best_rank, top5

# ============================================================
# 10. RUN FULL TEST SUBMISSION
# ============================================================

pred_map = {}
debug_records = []

print("\n=== START FULL TEST INFERENCE ===")
print("Number of test rows:", len(test_df))
print("Per row forward count:", len(TTA_PERMS) * len(PERMS))

for row_idx, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Test inference"):
    pred_order, pred_rank, top5 = predict_row(row, TEST_IMG_DIR)

    pred_map[str(row["Id"])] = answer_to_str(pred_rank)

    debug_records.append({
        "Id": row["Id"],
        "pred_rank": answer_to_str(pred_rank),
        "pred_order": answer_to_str(pred_order),
        "top1_score": top5[0][1],
        "top1_order": answer_to_str(top5[0][0]),
        "top2_score": top5[1][1],
        "top2_order": answer_to_str(top5[1][0]),
        "top3_score": top5[2][1],
        "top3_order": answer_to_str(top5[2][0]),
    })

    print(f"[{row_idx+1}/{len(test_df)}] Id={row['Id']} pred={pred_rank}")

    # 중간 저장: 세션 터져도 일부 결과 보존
    if (row_idx + 1) % 10 == 0:
        partial_debug_path = OUTPUT_DIR / "partial_debug_qwen25vl_base_none_logprob_tta_balanced4.csv"
        pd.DataFrame(debug_records).to_csv(partial_debug_path, index=False)
        print("Partial debug saved:", partial_debug_path)

debug_path = OUTPUT_DIR / "debug_qwen25vl_base_none_logprob_tta_balanced4.csv"
pd.DataFrame(debug_records).to_csv(debug_path, index=False)
print("Saved debug:", debug_path)

submission = sample_df.copy()
submission["Answer"] = submission["Id"].astype(str).map(pred_map)

missing = submission[submission["Answer"].isna()]
assert len(missing) == 0, f"Missing predictions: {missing.head()}"

for x in submission["Answer"]:
    vals = parse_answer(x)
    assert is_perm(vals), f"Invalid prediction: {x}"

assert submission["Id"].astype(str).tolist() == sample_df["Id"].astype(str).tolist(), "ID order mismatch"

submission_path = OUTPUT_DIR / "submission_qwen25vl_base_none_logprob_tta_balanced4.csv"
submission.to_csv(submission_path, index=False)

print("\nSaved submission:", submission_path)
print("DONE")